version: "3.3"

services:
  nextjs:
    build:
      context: .
    ports:
      - 3005:3005
    volumes:
      - ./usr/src/app/front
      - /usr/src/app/front/node_modules
      - /usr/src/app/front/.next
    environment:
      - BOOKS_API_URL=http://localhost:3005
      - GOODREADS_API_URL=http://nodejs:3000
    depends_on: 
      - nodejs
    command: bash -c "yarn build && yarn start"

  nodejs:
    build:
      context: .
      dockerfile: ./servidor_proxy/teste_ti_frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./servidor_proxy/teste_ti_frontend:/usr/src/app/api
      - /usr/src/app/api/node_modules
    command: npm start
      
  